default: emscripten build-retroarch

# TODO: migrate to latest version
fetch-emscripten:
    git submodule update
    cd emsdk && ./emsdk install 2.0.15 && ./emsdk activate 2.0.15

patch-emscripten:
    #!/usr/bin/env bash
    cd emsdk
    patch -u -p0 -i ../patches/emscripten.patch || true

emscripten: fetch-emscripten patch-emscripten

build-retroarch:
    #!/usr/bin/env bash
    cd RetroArch
    cp ../patches/retroarch.patch ./
    git apply retroarch.patch
    # emmake ./dist-cores.sh emscripten

core-build-mgba:
    #!/usr/bin/env bash
    . ./emsdk/emsdk_env.sh
    cd cores/mgba || (git submodule update && cd cores/mgba || exit)
    emmake make -f Makefile.libretro platform="emscripten"
    # make -f ./Makefile.libretro